events {}

http {
    log_format detailed '$remote_addr - $remote_user [$time_local] '
                        '"$request" $status $body_bytes_sent '
                        '"$http_referer" "$http_user_agent" '
                        '$request_time "$args"';

    access_log /var/log/nginx/access.log detailed;

    server {
        listen 80;
        root /var/www/html;
        index index.html index.php app.php;

        # Serve static files
        location / {
            try_files $uri $uri/ /index.html;
        }

        # Pass PHP requests to the PHP-FPM container
        location ~ \.php$ {
            fastcgi_pass   php:9000;
            fastcgi_index  index.php;
            # This line is critical for finding files in subfolders
            fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include        fastcgi_params;
        }
    }
}